### ISSUE TITLE
Crawling Up Blocks Visual bug

### ISSUE THREAD

**Issue by PuppyDougan7** [Retro64Mod/Retro64Mod.github.io#35] opened 2022-03-24 01:50 UTC
when crawling into a special set of block this happens

https://user-images.githubusercontent.com/91709867/159825907-e56240e1-bd44-499b-adfe-46bff479f75f.mp4

**Comment by dylanpdx** [comment] 2022-03-24 21:41
Duplicate of #8

**Closed by dylanpdx** 2022-03-24 21:41 UTC
Labels: bug, duplicate
