### ISSUE TITLE
BitDefender is detecting Java.Trojan.GenericGBA.31457 in the SM64Sounds.class

### ISSUE THREAD

**Issue by SolarNyan** [Retro64Mod/Retro64Mod.github.io#87] opened 2022-05-03 21:19 UTC
BitDefender seems to think the SM64Sounds.class file has a Java trojan imbedded in it.

What is this file, actually? It only showed up in my mods folder today and it hasn't shown up again since rerunning the game.

**Comment by dylanpdx** [comment] 2022-05-03 21:37
Duplicate of #73 #74 and #79

It's a false positive with the script that deals with extracting audio from a SM64 rom & there's not much I can do about it, sadly

> If you want to be absolutely sure it's safe, review the source code in the following repositories & compile everything using the instructions in the Readme files:
> 
> https://github.com/Retro64Mod/libsm64-retro64
> https://github.com/Retro64Mod/Retro64Mod
> https://github.com/Retro64Mod/sm64_asset_builder (currently no build instructions for this, but installing the pyinstaller package and making a single file out of genfiles.py should work)

**Closed by dylanpdx** 2022-05-03 21:37 UTC

**Comment by SolarNyan** [comment] 2022-05-03 22:29
I believe it's possible to present your files to these services to get them whitelisted, yeah? At least, I know that's how Microsoft handles it with their built-in Windows security.
