### ISSUE TITLE
17 Antiviruses flag the .JAR file as a virus, Why?

### ISSUE THREAD

**Issue by JamesMakesStuff** [Retro64Mod/Retro64Mod.github.io#79] opened 2022-04-30 14:57 UTC
So, I downloaded this mod JAR from https://retro64mod.github.io/, I downloaded it, Then my windows defender went off, so I put the file through VirusTotal, and this is what happened:
![image](https://user-images.githubusercontent.com/104538886/166110571-98858962-5b35-495f-8ca9-e625ecdd6c8e.png)
Is it safe to download currently?
Also, My friend Sammy3968 found this, And I Tested it.

**Comment by dylanpdx** [comment] 2022-04-30 15:28
Duplicate of #73 and #74
tl;dr, I don't know why it's flagged as a virus (possibly because of the inclusion of .dll files in the jar?), but the version you linked above is safe

If you want to be absolutely sure it's safe, review the source code in the following repositories & compile everything using the instructions in the Readme files:

https://github.com/Retro64Mod/libsm64-retro64
https://github.com/Retro64Mod/Retro64Mod
https://github.com/Retro64Mod/sm64_asset_builder (currently no build instructions for this, but installing the pyinstaller package and making a single file out of genfiles.py should work)

**Closed by dylanpdx** 2022-04-30 15:28 UTC
