### ISSUE TITLE
Crashing with error code -1

### ISSUE THREAD

**Issue by DizzyTwinss** [Retro64Mod/Retro64Mod.github.io#156] opened 2022-11-20 17:47 UTC
**Describe the bug**
When I try to load, or create a new world, at world loading (or creating) it would crash.
**Minecraft Version**
1.18.2

**Mod Version**
Forge 40.1.85

**Minecraft launcher**
Enter the launcher you are using, i.e Vanilla, MultiMC, CurseForge, etc.

**Please attach Screenshots or Crash logs if relevant to the bug**
[crash-2022-11-20_12.36.13-server.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/10050334/crash-2022-11-20_12.36.13-server.txt)
[crash-2022-11-20_12.39.13-server.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/10050335/crash-2022-11-20_12.39.13-server.txt)

**Desktop**
 - OS: Windows
 - Version: 10 21H2

**Comment by dylanpdx** [comment] 2022-11-20 18:36
Duplicate of #148 

This is an OptiFine issue, not related to this mod.
See https://github.com/sp614x/optifine/issues/6974

**Closed by dylanpdx** 2022-11-20 18:36 UTC
Labels: bug
